language: node_js
node_js:
- '10'
cache: npm
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: YQlx5MEvY6yBbUz8dCdHco9bh8g5VJDjHGm5InGthRBA0QR6E3d1skuRCRx4CfIdjLV/+K3xAGpk2RNuU7GKu81kmx5eKavLXKBhQWoLdXg+NxAdkgwic+GQzLEbULh7kaFLR0iIuHpAJ/R69AsGpYMJ2vLa/SvTZT21FKaffu7ntmcqwH10FjxhfXXUnkJlXbR/HT5L0eTxS2ZSZpZi6xi6iS2ZXIWcnLzep1s1bzGBE9S8Fv3kjEL6nzVt/7wpndXughUCr1pgK09QTX/Hqx6JmMLStcuNLdJZIIEkP3eDXQOhMHzytIt8Ef6YVD8tTtiVMFTIpd+scrfGf8EbZmj82DDzN9DpCARwvpD5NjPgjrwELV8PimkMaNiMwfxwV39MheFNEs9iVuSIyJO/CuyeMadjIpltxr/y0/s2cL6KFYLtt1Qk6QVEfUxJBU8ho08pNNuOplK+9P9ENB2ZkeDwkm5JrKiBdK561MxKyjAg0OJmU8Ssd/8q7uYuEChJQyaCc/9/zTCto8j2E/Ta+qZlqyryFY60DoBc98uTtm/RKY2/IMiAXIf/Z+VmA8gg3w7xTxZ2rjBDH02M3+xktiYxrP+JSQXkrTojHaM/2GnnPCURiU0SwiSLFE5n1RRjXLcFYH4jcrxOQckmyj2RjtJCpckywdtia2C99PPhjkU=
    app: strv-addressbook-dantas-robert
